
                ifndef _GAME_CELESTIAL_OBJECT_UTILS_INCLUDE_
                define _GAME_CELESTIAL_OBJECT_UTILS_INCLUDE_

                module Utils

                include "FindElement.asm"
                include "SetLocation.asm"
                include "SetRotator.asm"
                include "SetMatrix.asm"
                include "SetVelocity.asm"
                include "SetAcceleration.asm"
                include "SetFlags.asm"
                include "SetMeshInfo.asm"
                include "AddObject.asm"

                endmodule

                endif ; ~_GAME_CELESTIAL_OBJECT_UTILS_INCLUDE_
