
                ifndef _STRUCTURE_FACE_INCLUDE_
                define _STRUCTURE_FACE_INCLUDE_

                struct FFace
Primitive       DB #00                                                          ; тип римитива
Queue           DB #00                                                          ; 
Color           FColor

                ends

                endif ; ~_STRUCTURE_FACE_INCLUDE_
