
                ifndef _STRUCTURE_FACE_INCLUDE_
                define _STRUCTURE_FACE_INCLUDE_

                struct FFace
Primitive       DB #00                                                          ; тип примитива
Queue           DB #00                                                          ; 
Normal          DB #00                                                          ; индекс нормали примитива

                ends

                endif ; ~_STRUCTURE_FACE_INCLUDE_
