
                ifndef _STRUCTURE_MESH_BASE_INCLUDE_
                define _STRUCTURE_MESH_BASE_INCLUDE_

                include "Color.inc"
                include "Normal.inc"
                include "Position.inc"
                include "Vertex.inc"
                include "Face.inc"
                include "Mesh.inc"
                include "MeshInfo.inc"

                endif ; ~_STRUCTURE_MESH_BASE_INCLUDE_
