
                ifndef _STRUCTURE_NORMAL_INCLUDE_
                define _STRUCTURE_NORMAL_INCLUDE_

                struct FNormal
X               DW #0000                                                        ; FFixed214
Y               DW #0000                                                        ; FFixed214
Z               DW #0000                                                        ; FFixed214

                ends

                endif ; ~_STRUCTURE_NORMAL_INCLUDE_
