
                ifndef _STRUCTURE_POSITION_INCLUDE_
                define _STRUCTURE_POSITION_INCLUDE_

                define ZERO_POSITION {   0,   0,   0 }

                struct FPosition
X               DW #0000                                                        ; FFixed1814
Y               DW #0000                                                        ; FFixed1814
Z               DW #0000                                                        ; FFixed1814

                ends

                endif ; ~_STRUCTURE_POSITION_INCLUDE_
