
                ifndef _GAME_CELESTIAL_OBJECT_UTILS_SPACE_OBJECT_ARRAY_INCLUDE_
                define _GAME_CELESTIAL_OBJECT_UTILS_SPACE_OBJECT_ARRAY_INCLUDE_

                include "FindElement.asm"
                include "SetLocation.asm"
                include "SetRotator.asm"
                include "SetMatrix.asm"
                include "SetVelocity.asm"
                include "SetAcceleration.asm"
                include "SetFlags.asm"
                include "SetMeshInfo.asm"
                include "AddObject.asm"

                endif ; ~_GAME_CELESTIAL_OBJECT_UTILS_SPACE_OBJECT_ARRAY_INCLUDE_
