
                ifndef _GAME_CELESTIAL_OBJECT_MATH_INCLUDE_
                define _GAME_CELESTIAL_OBJECT_MATH_INCLUDE_

                module Math

                include "RotateVector.asm"
                include "RotateLocation.asm"
                include "MultiplyMatrixByVector.asm"
                include "PerspectiveProjection.asm"
                include "TransformVertex.asm"
                include "CrossProduct2D.asm"

                endmodule

                endif ; ~_GAME_CELESTIAL_OBJECT_MATH_INCLUDE_
