
                ifndef _STRUCTURE_ROTATOR_INCLUDE_
                define _STRUCTURE_ROTATOR_INCLUDE_

                struct FRotator
Roll            FFixed214                                                       ; rotation around the forward axis (around Z axis)
Pitch           FFixed214                                                       ; rotation around the right axis (around X axis)
Yaw             FFixed214                                                       ; rotation around the up axis (around Y axis)

                ends

                endif ; ~_STRUCTURE_ROTATOR_INCLUDE_
