Character_FTRAM_1       EQU Parallax_FTRAM_1 + Parallax_RealSize_1
Character_Format_1      EQU FT_ARGB1555
Character_Width_1       EQU 64
Character_Height_1      EQU 64
Character_Stride_1      EQU 128
Character_Size_1        EQU 3200                ; #0E00
Character_RealSize_1    EQU 8192
Character_Page_1        EQU 17
Character_RAM_1         EQU #C000

Character_FTRAM_2       EQU Character_FTRAM_1 + Character_RealSize_1
Character_Format_2      EQU FT_ARGB1555
Character_Width_2       EQU 64
Character_Height_2      EQU 64
Character_Stride_2      EQU 128
Character_Size_2        EQU 3086                ; #0E00
Character_RealSize_2    EQU 8192
Character_Page_2        EQU 17
Character_RAM_2         EQU #CE00

Character_FTRAM_3       EQU Character_FTRAM_2 + Character_RealSize_2
Character_Format_3      EQU FT_ARGB1555
Character_Width_3       EQU 64
Character_Height_3      EQU 64
Character_Stride_3      EQU 128
Character_Size_3        EQU 3243                ; #0E00
Character_RealSize_3    EQU 8192
Character_Page_3        EQU 17
Character_RAM_3         EQU #DC00


Character_FTRAM_4       EQU Character_FTRAM_3 + Character_RealSize_3
Character_Format_4      EQU FT_ARGB1555
Character_Width_4       EQU 64
Character_Height_4      EQU 64
Character_Stride_4      EQU 128
Character_Size_4        EQU 3335                ; #0E00
Character_RealSize_4    EQU 8192
Character_Page_4        EQU 17
Character_RAM_4         EQU #EA00

Character_FTRAM_5       EQU Character_FTRAM_4 + Character_RealSize_4
Character_Format_5      EQU FT_ARGB1555
Character_Width_5       EQU 64
Character_Height_5      EQU 64
Character_Stride_5      EQU 128
Character_Size_5        EQU 3470                ; #0E00
Character_RealSize_5    EQU 8192
Character_Page_5        EQU 17
Character_RAM_5         EQU #F800

Character_FTRAM_6       EQU Character_FTRAM_5 + Character_RealSize_5
Character_Format_6      EQU FT_ARGB1555
Character_Width_6       EQU 64
Character_Height_6      EQU 64
Character_Stride_6      EQU 128
Character_Size_6        EQU 3559                ; #0E00
Character_RealSize_6    EQU 8192
Character_Page_6        EQU 18
Character_RAM_6         EQU #C600

Character_FTRAM_7       EQU Character_FTRAM_6 + Character_RealSize_6
Character_Format_7      EQU FT_ARGB1555
Character_Width_7       EQU 64
Character_Height_7      EQU 64
Character_Stride_7      EQU 128
Character_Size_7        EQU 3166                ; #0E00
Character_RealSize_7    EQU 8192
Character_Page_7        EQU 18
Character_RAM_7         EQU #D400

Character_FTRAM_8       EQU Character_FTRAM_7 + Character_RealSize_7
Character_Format_8      EQU FT_ARGB1555
Character_Width_8       EQU 64
Character_Height_8      EQU 64
Character_Stride_8      EQU 128
Character_Size_8        EQU 3110                ; #0E00
Character_RealSize_8    EQU 8192
Character_Page_8        EQU 18
Character_RAM_8         EQU #E200