                ifndef _FIXED_2_14_CONST_
                define _FIXED_2_14_CONST_
FIXED_214_MAX_P EQU 0x7FFF                                                      ; maximum positive number
FIXED_214_MIN_P EQU 0x0001                                                      ; minimum positive number
FIXED_214_MAX_N EQU 0xFFFF                                                      ; maximum negative number
FIXED_214_MIN_N EQU 0x8001                                                      ; minimum negative number
FIXED_214_ONE   EQU 0x4000                                                      ; 1.0 value
                endif ; ~_FIXED_2_14_CONST_
