                ifndef _FIXED_18_14_CONST_
                define _FIXED_18_14_CONST_
FIXED_1814_MAX_P EQU 0x7FFFFFFF                                                 ; maximum positive number
FIXED_1814_MIN_P EQU 0x00000001                                                 ; minimum positive number
FIXED_1814_MAX_N EQU 0xFFFFFFFF                                                 ; maximum negative number
FIXED_1814_MIN_N EQU 0x80000001                                                 ; minimum negative number
                endif ; ~_FIXED_18_14_CONST_
