
                ifndef _GAME_CELESTIAL_OBJECT_DRAW_CELESTIAL_OBJECT_
                define _GAME_CELESTIAL_OBJECT_DRAW_CELESTIAL_OBJECT_

Draw:           RET

                endif ; ~_GAME_CELESTIAL_OBJECT_DRAW_CELESTIAL_OBJECT_
