
                ifndef _GAME_CELESTIAL_OBJECT_INCLUDE_
                define _GAME_CELESTIAL_OBJECT_INCLUDE_

                module CelestialObject

                include "Math/Include.inc"
                include "UpdateSolarSystem.asm"
                include "MoveCelestialObject.asm"
                include "DrawCelestialObject.asm"

                endmodule

                endif ; ~_GAME_CELESTIAL_OBJECT_INCLUDE_
